eventhub_credentials/node_logger:
  ros__parameters:
      conn_str: "Endpoint=sb://ros2-messages.servicebus.windows.net/;SharedAccessKeyName=main;SharedAccessKey=99K4ni0KTODp3Vr+lGxDwoikdv8MDajVQU/b6pJOipo=;EntityPath=oit-eventhub"
      eventhub_name: "oit-eventhub"